# Generated by Django 3.2.8 on 2021-11-11 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(default='media/inst/default_inst.png', upload_to='inst/')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_inst', models.IntegerField(default=1)),
                ('img', models.ImageField(default='media/room/default_room.png', upload_to='room/')),
            ],
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('end_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thuid', models.CharField(default='default-thuid', max_length=64)),
                ('openid', models.CharField(default='default-openid', max_length=64)),
                ('balance', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Other'), (100, 'Unauthorized')], default=100)),
                ('group', models.ManyToManyField(to='appointment.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.usergroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.room')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('end_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('price', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Finished'), (5, 'Outdated')], default=1)),
                ('inst', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.instrument')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentTypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.usergroup')),
                ('insttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.instrumenttype')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='room',
            field=models.ManyToManyField(to='appointment.Room'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.instrumenttype'),
        ),
        migrations.CreateModel(
            name='ForbiddenRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('end_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('status', models.IntegerField(choices=[(1, 'Fix'), (2, 'Activity'), (100, 'Other')], default=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.usergroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.room')),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('end_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('status', models.IntegerField(choices=[(1, 'Activity'), (2, 'Fix'), (100, 'Other')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.usergroup')),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.instrument')),
            ],
        ),
    ]
